# Generated by Django 6.0.2 on 2026-02-13 13:33

from django.db import migrations

def seed_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    Product.objects.create(
        product_id="P001",
        name="Rice Bag",
        available_stocks=50,
        unit_price=1000,
        tax_percentage=5
    )

    Product.objects.create(
        product_id="P002",
        name="Oil Can",
        available_stocks=30,
        unit_price=500,
        tax_percentage=12
    )

    Product.objects.create(
        product_id="P003",
        name="Sugar",
        available_stocks=40,
        unit_price=60,
        tax_percentage=5
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_products),
    ]
