# Generated by Django 6.0.2 on 2026-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('available_count', models.PositiveIntegerField()),
            ],
        ),
    ]
