# Generated by Django 6.0.2 on 2026-02-13 14:15

from django.db import migrations

def seed_shopdenomination(apps, schema_editor):
    ShopDenomination = apps.get_model('products', 'ShopDenomination')

    ShopDenomination.objects.create(value=500, available_count=10)
    ShopDenomination.objects.create(value=50, available_count=20)
    ShopDenomination.objects.create(value=20, available_count=30)
    ShopDenomination.objects.create(value=10, available_count=50)
    ShopDenomination.objects.create(value=5, available_count=50)
    ShopDenomination.objects.create(value=2, available_count=100)
    ShopDenomination.objects.create(value=1, available_count=200)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shopdenomination'),
    ]

    operations = [
        migrations.RunPython(seed_shopdenomination),
    ]
